name: app_cf_marvel
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: 5.4.1
  mobx: ^2.3.0+1
  flutter_mobx: ^2.2.0+2
  get_it: ^7.6.7
  provider: ^6.0.4
  path_provider: ^2.1.3
  sqflite: ^2.3.3+1
  cupertino_icons: ^1.0.6
  path: ^1.9.0
  app_settings: ^5.1.1 #For notifications
  permission_handler: ^11.3.1  #For notifications
  flutter_local_notifications: ^17.2.1+1 #For notifications
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  mobx_codegen: ^2.6.0+1
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
  - assets/